sample_rate: 32000
n_mels: 96
n_fft: 512
hop_length: 288
window: hamming
fmin: 400
band_low_freq: 400
fmax: 14999
butterworth_order: 0
band_high_freq: 8499
p_loud: 0.2
p_gaus: 0.0
p_spec: 0.0
freq_masks: 0
time_masks: 2
freq_width: 58
time_width: 18
mixup_prob: 0.4
batch_size: 16
pos_neg_ratio: 1
epochs_per_fold: 40
use_pcen: true
pcen_time_constant: 0.45
pcen_gain: 0.9500000000000001
pcen_bias: 2.75
pcen_power: 0.4
stacks: 3
pooling: avg
l2: 0.0001
lr: 0.001
dropout: 0.0
loss: FOCAL
gamma: 2
alpha: 0.2
loud_min_db: -36.0
loud_max_db: -18.0
gaus_snr_min: 10
gaus_snr_max: 15
mixup_alpha: 0.30000000000000004
tuner/epochs: 34
tuner/initial_epoch: 0
tuner/bracket: 1
tuner/round: 0
